version: "3.8"

services:
  api-gateway:
    build: ./api-gateway
    ports:
      - "3000:3000"
    env_file: ./api-gateway/.env
    restart: unless-stopped
    depends_on:
      - redis
      - rabbitmq
      - mongodb
    environment:
      - REDIS_URL=redis://redis:6379
      - RABBITMQ_URL=amqp://rabbitmq:5672
      - MONGODB_URL=mongodb://mongodb:27017/mydatabase
      - IDENTITY_SERVICE_URL=http://identity-service:3001
      - POST_SERVICE_URL=http://post-service:3002
      - MEDIA_SERVICE_URL=http://media-service:3003
      - SEARCH_SERVICE_URL=http://search-service:3004

  identity-service:
    build: ./identity-service
    env_file: ./identity-service/.env
    restart: unless-stopped
    depends_on:
      - redis
      - rabbitmq
      - mongodb
    environment:
      - REDIS_URL=redis://redis:6379
      - RABBITMQ_URL=amqp://rabbitmq:5672
      - MONGODB_URL=mongodb://mongodb:27017/mydatabase

  post-service:
    build: ./post-service
    env_file: ./post-service/.env
    restart: unless-stopped
    depends_on:
      - redis
      - rabbitmq
      - mongodb
    environment:
      - REDIS_URL=redis://redis:6379
      - RABBITMQ_URL=amqp://rabbitmq:5672
      - MONGODB_URL=mongodb://mongodb:27017/mydatabase

  media-service:
    build: ./media-service
    env_file: ./media-service/.env
    restart: unless-stopped
    depends_on:
      - redis
      - rabbitmq
      - mongodb
    environment:
      - REDIS_URL=redis://redis:6379
      - RABBITMQ_URL=amqp://rabbitmq:5672
      - MONGODB_URL=mongodb://mongodb:27017/mydatabase

  search-service:
    build: ./search-service
    env_file: ./search-service/.env
    restart: unless-stopped
    depends_on:
      - redis
      - rabbitmq
      - mongodb
    environment:
      - REDIS_URL=redis://redis:6379
      - RABBITMQ_URL=amqp://rabbitmq:5672
      - MONGODB_URL=mongodb://mongodb:27017/mydatabase

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  redis_data:
  rabbitmq_data:
  mongodb_data:
